### ISSUE TITLE
python-pip (and python2-pip) not found on centos 7

### ISSUE THREAD

**Issue by gmalouf** [geerlingguy/ansible-role-pip#1]
I had to add the following to find pip

- name: install epel release package repo if not present
    yum: name=epel-release state=present

Perhaps split the tasks in debian vs RHEL?

**Comment by geerlingguy** [comment]
Strange... what version of RedHat / CentOS are you using?

**Comment by geerlingguy** [comment]
Note that I'm only testing on centos7: https://travis-ci.org/geerlingguy/ansible-role-pip — if using RHEL/CentOS 6 then you might need to also run the `geerlingguy.repo-epel` role prior to this role. And we could update the docs to reflect that.

**Comment by gmalouf** [comment]
Version I am using:

centos-release-7-3.1611.el7.centos.x86_64

**Comment by kakawait** [comment]
Same issue, `python-pip` is part of _EPEL_ repo as you installed yourself in your [`Dockerfile`](https://github.com/geerlingguy/docker-centos7-ansible/blob/master/Dockerfile#L18)

```
...
 && yum -y install deltarpm epel-release initscripts \
...
```

**Comment by geerlingguy** [comment]
Sorry about that! I've added a note in the README Requirements section.
