### ISSUE TITLE
Ubuntu 18.04 Server - python3-pip not working

### ISSUE THREAD

**Issue by BigCheeZ** [geerlingguy/ansible-role-pip#12]
When I run this role with pip_package set to "python3-pip" on a Ubuntu 18.04 Server I get the following error.

TASK [geerlingguy.pip : Ensure Pip is installed.] *******************************************************************************************************************************************************************************************
fatal: []: FAILED! => {"changed": false, "msg": "No package matching 'python3-pip' is available"}

**Comment by jinmiaoluo** [comment]
on Ubuntu 18.04.1. python3-pip has be move to universe repository . Please consider to add universe repository @BigCheeZ 
```
apt_repository

**Comment by zx1986** [comment]
not fix yet :-(
