### ISSUE TITLE
Debian pip issues

### ISSUE THREAD

**Issue by jstoja** [geerlingguy/ansible-role-pip#2]
Hello,

It seems that there is an issue with the version of pip and the version of the packages with debian.
I found the issue and resolution here: https://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread/27341847#27341847

Using easy_install might fix the role!

**Comment by CumpsD** [comment]
I am having the following error, is this related?

```
TASK [pip : Ensure pip_install_packages are installed.] ******************************************************************************************************************************************
failed: [localhost] (item=awscli) => {"changed": false, "cmd": "/home/cumpsd/.local/bin/pip2 install awscli", "item": "awscli", "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/home/cumpsd/.local/bin/pip2\", line 7, in <module>\n    from pip import main\nImportError: cannot import name main\n"}
        to retry, use: --limit @/home/cumpsd/.dotfiles/ansible/system.retry
```

I only have this in my playbook:
```
    pip_install_packages:
      - awscli
```

Running pip install on the CLI works

**Comment by jstoja** [comment]
What does output “which pip && pip -v” when you run it on the machine? It’s prossibly related yes.

**Comment by CumpsD** [comment]
Just fixed it (https://github.com/CumpsD/dotfiles#pip-errors) by uninstalling pip (`python -m pip uninstall pip`) and letting the role install it

**Comment by jstoja** [comment]
This was probably because you had pip installed for your user (`get-pip.py --user` or something).

**Comment by jstoja** [comment]
The issue you might got when having this problem is that when pip will try to install some packages, it'll fail with the message `ImportError: cannot import name 'IncompleteRead'`. The reason is explained in the StackOverflow link in the first message of this issue.
