### ISSUE TITLE
CentOS 8 / EL 8, python-pip is not an available package

### ISSUE THREAD

**Issue by HauptJ** [geerlingguy/ansible-role-pip#24]
```    centos8hv: TASK [pip : Ensure Pip is installed.] ******************************************
    centos8hv: fatal: [localhost]: FAILED! => {"changed": false, "failures": ["No package python-pip available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

For CentOS 8 / EL 8, the correct package is python3-pip. I will fix this and make a PR.

```
[vagrant@centos8 ~]$ sudo dnf install python3-pip
Last metadata expiration check: 0:06:41 ago on Mon 28 Oct 2019 06:29:06 AM UTC.
Dependencies resolved.
===================================================================================================================== Package                Arch              Version                                         Repository            Size
=====================================================================================================================Installing:
 python3-pip            noarch            9.0.3-13.el8                                    AppStream             18 k
Installing dependencies:
 python36               x86_64            3.6.8-2.module_el8.0.0+33+0a10c0e1              AppStream             19 k
Enabling module streams:
 python36                                 3.6
```

**Comment by nilesingalls** [comment]
here's what's working for me in centos 8

  vars:
    pip_executable: /usr/local/bin/pip3
    pip_package: python3-pip

**Comment by hoxu** [comment]
Setting just `pip_package: python3-pip` seems to be enough on CentOS 8.

@HauptJ are you working on a PR?

**Comment by eslerm** [comment]
If you are using CentOS 8 with either Python 2 or 3, you should set both `pip_executable` and `pip_package` variables.

`python2-pip` and `python3-pip` are installable with CentOS 8's default dnf repos, but not `python-pip` (the default of `pip_executable`).

When these packages are installed, `pip2` and `pip3` are executable, but not `pip`. So, `pip_executable` will need to be manually set when using Python 2's pip on CentOS 8.


@nilesingalls I believe you mean `pip3`, not `python3-pip`.

**Comment by fgierlinger** [comment]
I just submitted PR #30 which addresses this issue.

**Comment by carlba** [comment]
Yes this should really be a part of this role having to handle this in all roles kinda negates the purpose of this role alltogether

**Comment by prodog8** [comment]
I also get a python-pip error.
I don't know how to solve.

`"changed": false, "failures": ["No package python-pip available."], "msg": "Failed to install some of the specified packages"`

Configuration (defaults/main.yml)
```
pip_package: python3-pip
pip_executable: pip3 "{{ 'pip3' if pip_package.startswith('python3') else 'pip' }}"
```

**Comment by prodog8** [comment]
I was able to solve it

**Comment by geerlingguy** [comment]
PR was merged but I've also gone ahead and changed the default for this role to `python3-pip`.
