### ISSUE TITLE
[DEPRECATION WARNING]: Invoking "pip" only once while using a loop via squash_actions is deprecated

### ISSUE THREAD

**Issue by zen** [geerlingguy/ansible-role-pip#36]
Hi Jeff

I'm getting following warning when using the role:
```
[DEPRECATION WARNING]: Invoking "pip" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items
and specifying `name: "{{ item.name | default(item) }}"`, please use `name: '{{
 pip_install_packages }}'` and remove the loop. This feature will be removed in
 version 2.11.
```

I'm setting variable like this in group_vars file:
```
pip_install_packages:
      - docker
      - docker-compose
```

roles
- geerlingguy.docker, 2.9.0
- geerlingguy.pip, 2.0.0

**Comment by fgierlinger** [comment]
This issue is still relevant, the pip module will change its behavior with Ansible 2.11 .

**Comment by fgierlinger** [comment]
@geerlingguy could you reopen this issue. It is still relevant.

**Comment by geerlingguy** [comment]
@fgierlinger - I'll reopen but I'm not sure what other option there is. It's deprecated, sure, but it will still work, just slower than passing in an entire array at once.

AFAICT, there's still no easy way to pass in a full set of installable things providing customized options within that set without using a loop :(

**Comment by fgierlinger** [comment]
@geerlingguy See PR #42 where I fixed the deprecation warning with using `loop` instead of `with_x`
