### ISSUE TITLE
Failed install on debian10 

### ISSUE THREAD

**Issue by upszot** [geerlingguy/ansible-role-pip#51]
I play the ansible in Vagrant 

servtest.vm.box = "generic/debian10"

and failed  "TASK [geerlingguy.pip : Ensure pip_install_packages are installed."

`
- name: install pip
  include_role:
    name: geerlingguy.pip
    apply:
      become: yes
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: passlib
    pip_executable: /usr/bin/pip3
`
Adjunt normal log...
[ansible_output.log](https://github.com/geerlingguy/ansible-role-pip/files/9647813/ansible_output.log)

and adjunt   verbose  log

[ansible_output.log](https://github.com/geerlingguy/ansible-role-pip/files/9647802/ansible_output.log)

thanks

**Comment by dimsunv** [comment]
Try add play:
```
- name: upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
```
