### ISSUE TITLE
Can't install role from Ansible Galaxy: error: unable to compare role versions

### ISSUE THREAD

**Issue by dbethke** [geerlingguy/ansible-role-pip#60]
Did something change with geerling.pip (latest)?
 I'm getting errors all of a sudden, but it could just be on my end.

```
[WARNING]: - geerlingguy.pip was NOT installed successfully: Unable to compare
role versions (1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 2.0.0, 2.1.0, 2.2.0,
master) to determine the most recent version due to incompatible version
formats. Please contact the role author to resolve versioning conflicts, or
specify an explicit role version to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

I wasn't specifying a version before--just the name. I imagine that means I'm using latest. 
If I specify version`2.2.0` it works for me again.

**Comment by FuzzyMistborn** [comment]
Seeing this too, so not just you.

Seems to be an issue on Ansible Galaxy.  I see this when I visit [the page](https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/pip/):

```
Failed to load role versions
Error 404 - : <!doctype html> <html lang="en"> <head> <title>Not Found</title> </head> <body> <h1>Not Found</h1><p>The requested resource was not found on this server.</p> </body> </html>
```

**Comment by geerlingguy** [comment]
This seems to be an issue with Galaxy. I've opened a forum topic to ask for help: [Role import from GitHub results in "master" release, not the tag release, breaking installs](https://forum.ansible.com/t/role-import-from-github-results-in-master-release-not-the-tag-release-breaking-installs/1856)

**Comment by pniaps** [comment]
Same problem here.

**Comment by distributev** [comment]
Same here.

Any workaround? 

I use things like 

dependencies:
  - geerlingguy.pip

in meta/main.yml 

and 

roles:
  - geerlingguy.pip
  
in
 
requirements-roles.yml

I believe I need to add explicit version like 2.2.0 or 3.0.0 but not sure how and where in both meta/main.yml and requirements-roles.yml or just in one file?

**Comment by geerlingguy** [comment]
I've published a blog post about this: [Ansible Galaxy error 'Unable to compare role versions'](https://www.jeffgeerling.com/blog/2023/ansible-galaxy-error-unable-compare-role-versions).

**Comment by geerlingguy** [comment]
Also related: https://github.com/ansible/galaxy_ng/pull/1946 (the fix)
