### ISSUE TITLE
centos7

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-pip#9]
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'python3-pip' found available, installed or updated", "rc": 126, "results": ["No package matching 'python3-pip' found available, installed or updated"]}
```

**Comment by jevonearth** [comment]
You need to enable the EPEL repos first. 

Use the `geerlingguy.repo-epel` role before `geerlingguy.pip`. Or just enable epel manually. :)

**Comment by mariojmdavid** [comment]
agree with @jevonearth , but I think this role should have a dependency on the repo-epel role for centos7
of course this would "split" into centos7/ubuntu tasks
I hit the same issue, and installed the repo-epel, maybe just a nice to have, you decide
